"""
Fine-tune a concept-steered LoRA adapter on data generated by generate_training_data.py.

The resulting adapter, when loaded on top of the base model, reproduces the target
behaviour (e.g. more technical, more optimistic) without any runtime steering
vector injection.

Usage:
    python train_lora.py --concept technical_simple
    python train_lora.py --concept optimistic_pessimistic --rank 16 --epochs 3
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import List, Optional

from datasets import Dataset
from peft import LoraConfig, TaskType
from trl import SFTConfig, SFTTrainer

import config
from extraction import load_model_and_tokenizer

logger = logging.getLogger(__name__)

LORA_DATA_DIR = config.DATA_DIR / "lora_training"
LORA_ADAPTERS_DIR = config.DATA_DIR / "lora_adapters"


def _load_jsonl(path: Path) -> List[dict]:
    records = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def _format_records(records: List[dict], tokenizer) -> List[str]:
    """Apply the model's chat template to produce fully-formatted training strings."""
    return [
        tokenizer.apply_chat_template(
            record["messages"],
            tokenize=False,
            add_generation_prompt=False,
        )
        for record in records
    ]


def train_lora(
    concept_name: str,
    data_path: Path,
    output_dir: Path,
    rank: int = 16,
    lora_alpha: int = 32,
    lora_dropout: float = 0.05,
    target_modules: Optional[List[str]] = None,
    epochs: int = 3,
    lr: float = 2e-4,
    batch_size: int = 4,
    gradient_accumulation_steps: int = 2,
    max_seq_length: int = 512,
) -> None:
    if target_modules is None:
        target_modules = ["q_proj", "v_proj"]

    model, tokenizer = load_model_and_tokenizer()
    model.train()

    records = _load_jsonl(data_path)
    if not records:
        raise ValueError(f"No training records found in {data_path}")

    texts = _format_records(records, tokenizer)
    dataset = Dataset.from_dict({"text": texts})
    logger.info(
        "Loaded %d training examples for concept '%s' from %s",
        len(dataset), concept_name, data_path,
    )

    lora_config = LoraConfig(
        r=rank,
        lora_alpha=lora_alpha,
        target_modules=target_modules,
        lora_dropout=lora_dropout,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    # SFTConfig is the trl 1.x successor to passing TrainingArguments + SFT kwargs
    # separately. dataset_text_field and max_length live here, not on the trainer.
    sft_config = SFTConfig(
        output_dir=str(output_dir),
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        learning_rate=lr,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        logging_steps=10,
        save_strategy="epoch",
        fp16=(config.DEVICE == "cuda"),
        bf16=False,
        dataloader_num_workers=0,
        report_to="none",
        remove_unused_columns=True,
        dataset_text_field="text",
        max_length=max_seq_length,
    )

    trainer = SFTTrainer(
        model=model,
        args=sft_config,
        train_dataset=dataset,
        processing_class=tokenizer,
        peft_config=lora_config,
    )

    logger.info(
        "Starting LoRA training: concept=%s  rank=%d  alpha=%d  epochs=%d  lr=%g",
        concept_name, rank, lora_alpha, epochs, lr,
    )
    trainer.train()

    adapter_path = output_dir / "final"
    trainer.save_model(str(adapter_path))
    tokenizer.save_pretrained(str(adapter_path))
    logger.info("Saved LoRA adapter -> %s", adapter_path)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    parser = argparse.ArgumentParser(
        description="Train a concept-steered LoRA adapter from generated training data"
    )
    parser.add_argument(
        "--concept", required=True,
        help="Concept name to train (e.g. technical_simple).",
    )
    parser.add_argument("--rank", type=int, default=16, help="LoRA rank (default: %(default)s).")
    parser.add_argument("--lora-alpha", type=int, default=32)
    parser.add_argument("--lora-dropout", type=float, default=0.05)
    parser.add_argument(
        "--target-modules", nargs="+", default=["q_proj", "v_proj"],
        help="Model modules to apply LoRA to (default: q_proj v_proj).",
    )
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--grad-accum", type=int, default=2, help="Gradient accumulation steps.")
    parser.add_argument("--max-seq-length", type=int, default=512)
    parser.add_argument(
        "--data-dir", type=Path, default=LORA_DATA_DIR,
        help="Directory containing {concept}.jsonl files.",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=LORA_ADAPTERS_DIR,
        help="Root directory for adapters; adapter is saved to <output-dir>/<concept>/.",
    )
    args = parser.parse_args()

    data_path = args.data_dir / f"{args.concept}.jsonl"
    if not data_path.exists():
        logger.error("Training data not found: %s", data_path)
        logger.error(
            "Run first:  python generate_training_data.py --concepts %s", args.concept
        )
        return

    train_lora(
        concept_name=args.concept,
        data_path=data_path,
        output_dir=args.output_dir / args.concept,
        rank=args.rank,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        target_modules=args.target_modules,
        epochs=args.epochs,
        lr=args.lr,
        batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        max_seq_length=args.max_seq_length,
    )


if __name__ == "__main__":
    main()
